### PR TITLE
Font changes!

### PR DESCRIPTION
**Pull request by TheBinitGhimire**
Hi @ThePratikGyawali,

You shall review the changes I have made, and merge this Pull Request.

Thanks,
@TheBinitGhimire

### CODE REVIEW

**Comment by ThePratikGyawali** [comment]
That's awesome of you Binit, thank you for your suggestion! :)

**Comment by TheBinitGhimire** [comment]
You're welcome, @ThePratikGyawali dada!

**Comment by ThePratikGyawali** [comment]
Oh dada!

**Comment by TheBinitGhimire** [comment]
Yes, dada!

**Pull request merged**
